kind: pipeline
name: default

steps:
- name: publish
  image: golang
  environment:
    GOOS: linux
    PASSWORD:
      from_secret: password

- name: message
  image: ubuntu
  environment:
    BLABLA: linux
    PASSWORD:
      from_secret: password
  commands:
  - echo "hello world"
  - apt-get update
  - pwd
  - ls -ltra
  - cp README.md README.md1
  - ls -ltra
  - cp eks/terraform/preprod/* eks/terraform/.
  - ls -ltra
  - ls -ltrs eks/terraform/
  - cd eks/terraform/
  - pwd
  - printenv

- name: plan
  image: jmccann/drone-terraform:1
  working_dir: /drone/src/eks/terraform/
  plan: false