kind: pipeline
name: default

steps:
- name: publish
  image: golang
  environment:
    GOOS: linux
    PASSWORD:
      from_secret: password

- name: message
  image: ubuntu
  environment:
    BLABLA: linux
    PASSWORD:
      from_secret: password
  commands:
  - apt-get install unzip
  - wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
  - unzip terraform_0.11.10_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - terraform --version 
  - echo "hello world"
  - apt-get update
  - pwd
  - ls -ltra
  - cp README.md README.md1
  - ls -ltra
  - cp eks/terraform/preprod/* eks/terraform/.
  - ls -ltra
  - ls -ltrs eks/terraform/
  - cd eks/terraform/
  - pwd
  - printenv