kind: pipeline
name: default

steps:
- name: publish
  image: golang
  environment:
    GOOS: linux
    PASSWORD:
      from_secret: password

- name: message
  image: ubuntu
  environment:
    BLABLA: linux
    AWS_DEFAULT_REGION: us-east-1
    PASSWORD:
      from_secret: password
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY     
  commands:
  - apt-get update
  - apt-get install unzip
  - apt-get install -y wget
  - wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
  - unzip terraform_0.11.10_linux_amd64.zip
  - mv terraform /usr/local/bin/
  - terraform --version 
  - echo "hello world"
  - pwd
  - ls -ltra
  - cp README.md README.md1
  - ls -ltra
  - cp eks/terraform/preprod/* eks/terraform/.
  - ls -ltra
  - ls -ltrs eks/terraform/
  - cd eks/terraform/
  - pwd
  - printenv
  - terraform init
  - terraform plan -out kubernetes.tfplan -input=false
  - terraform apply kubernetes.tfplan
  - # Add users to config map
  - # Single quotes for environment vars
  - export KUBECONFIG="./kubeconfig"
  - terraform output config-map-aws-auth > config.yml
  - printf "\n" >> users.yml
  - #printf "  mapUsers: |\n" >> config.yml
  - while IFS="\n" read -r line;
      do printf "    %s\n" "$line" >> config.yml;
    done < users.yml
  - kubectl apply -f config.yml
