---
secrets:
  - metadata:
      name: kiam-server-tls
      namespace: devops
    data:
      ca.pem: "{{ vault_ca_pem }}"
      server-key.pem: "{{ vault_server_key_pem }}"
      server.pem: "{{ vault_server_pem }}"
  - metadata:
      name: kiam-agent-tls
      namespace: devops
    data:
      ca.pem: "{{ vault_ca_pem }}"
      agent-key.pem: "{{ vault_agent_key_pem }}"
      agent.pem: "{{ vault_agent_pem }}"
