---
- name: influx efs mount preprod
  mount:
    src: "{{ influx_efs_dns_name_preprod }}:/"
    path: "{{ influx_folder_preprod }}"
    state: present
    fstype: nfs4
    opts: "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev"
    fstab: /etc/fstab-preprod

- name: chronograf efs mount preprod
  mount:
    src: "{{ chronograf_efs_dns_name_preprod }}:/"
    path: "{{ chronograf_folder_preprod }}"
    state: present
    fstype: nfs4
    opts: "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev"
    fstab: /etc/fstab-preprod

- name: influx efs mount preprod
  mount:
    src: "{{ influx_efs_dns_name_prod }}:/"
    path: "{{ influx_folder_prod }}"
    state: present
    fstype: nfs4
    opts: "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev"
    fstab: /etc/fstab-prod

- name: chronograf efs mount preprod
  mount:
    src: "{{ chronograf_efs_dns_name_prod }}:/"
    path: "{{ chronograf_folder_prod }}"
    state: present
    fstype: nfs4
    opts: "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev"
    fstab: /etc/fstab-prod
