apiVersion: v1
kind: Service
metadata:
  name: {{ template "kiam.fullname" . }}-server
  labels:
    app: {{ include "kiam.name" . }}
    chart: {{ include "kiam.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: server
spec:
  clusterIP: None
  selector:
    app: {{ include "kiam.name" . }}
    release: {{ .Release.Name }}
    component: server
  ports:
  - name: grpclb
    port: {{ .Values.server.service.port }}
    targetPort: {{ .Values.server.service.targetPort }}
    protocol: TCP
