helmOperator:
  create: true
  tolerations:
  - key: "node.kubernetes.io/unschedulable"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  nodeSelector:
    dedicated: eks-components
git:
  url: ssh://git@github.com/kewlvishnu/kubernetes-flux
  branch: master
  path: staging/projects
  secretName: flux-git-deploy
  label: flux-sync-preprod
additionalArgs:
- "--connect=ws://fluxcloud"

tolerations:
- key: "node.kubernetes.io/unschedulable"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"
nodeSelector:
  dedicated: eks-components

memcached:
  tolerations:
  - key: "node.kubernetes.io/unschedulable"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  nodeSelector:
    dedicated: eks-components
  
