apiVersion: v1
kind: Service
metadata:
  name: {{ template "fluxcloud.fullname" . }}
  labels:
    app: {{ template "fluxcloud.name" . }}
    chart: {{ template "fluxcloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3032
  selector:
    app: {{ template "fluxcloud.name" . }}
    release: {{ .Release.Name }}
